### ISSUE TITLE
Marker calibration: multiple cubes, offset

### ISSUE THREAD

**Issue by ZdenekM** [robofit/arcor2_areditor#150]
AREditor version: 0.7.2.

- After calibration (clicking on the cube), there is always some offset - tried on different surfaces.
- Sometimes, there are more cubes.

![Screenshot_20200706-081723_AREditor](https://user-images.githubusercontent.com/1199396/86564307-4a292000-bf66-11ea-840b-1af6a7a4cdcb.jpg)

![Screenshot_20200706-082246_AREditor](https://user-images.githubusercontent.com/1199396/86564800-139fd500-bf67-11ea-8bd9-07cb3a047055.jpg)

![Screenshot_20200706-085648_AREditor](https://user-images.githubusercontent.com/1199396/86565015-6c6f6d80-bf67-11ea-8bb2-0e0688608d7d.jpg)

![Screenshot_20200706-085714_AREditor](https://user-images.githubusercontent.com/1199396/86565017-6d080400-bf67-11ea-98eb-7fdd4dd18462.jpg)

**Comment by xBambusekD** [comment]
For best calibration results, you should click on the calibration cube with the camera pointing straight down on the marker, otherwise there will always be some offset due to imperfect image processing of ARCore.
![Screenshot_20200708-203053_AREditor](https://user-images.githubusercontent.com/26470087/86956874-1dd5f500-c15a-11ea-8181-378dd500da85.jpg)

Regarding multiple cubes, can you describe steps on how to reproduce this issue?

**Comment by ZdenekM** [comment]
Hmm, today I had troubles with reproducing this. But I found one way, see video: https://photos.app.goo.gl/CSvbie9zzEiVgrYF6. 

[logs.txt](https://github.com/robofit/arcor2_editor/files/4894982/logs.txt)
